### ISSUE TITLE
FluidStack Crash CompactMachines 1.18

### ISSUE THREAD

**Issue by Deathlymad** [thraaawn/CompactMachines#110]
So... I am running a custom private modpack with compact machines, and the latest Forge Version for 1.7.10. The Problem occured as I was trying to configure the interface to transfer items. but everytime i am trying to open the GUI, it crashes. It seems to be an null fluid in the comtainer, Forge doesn't like it...

[13:27:05] [Server thread/WARN] [FML/]: ****************************************
[13:27:05] [Server thread/WARN] [FML/]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[13:27:05] [Server thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[13:27:05] [Server thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[13:27:05] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:20)
[13:27:05] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:30)
[13:27:05] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.FluidSharedStorage$Tank.<init>(FluidSharedStorage.java:22)
[13:27:05] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.FluidSharedStorage.<init>(FluidSharedStorage.java:37)...
[13:27:05] [Server thread/WARN] [FML/]: ****************************************
[13:27:05] [Server thread/ERROR] [Compact Machines/]: Could not create instance of class: class org.dave.CompactMachines.integration.fluid.FluidSharedStorage
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedConstructorAccessor194.newInstance(Unknown Source)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.handler.SharedStorageHandler.getStorage(SharedStorageHandler.java:161)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.handler.SharedStorageHandler.getStorage(SharedStorageHandler.java:146)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.handler.SharedStorageHandler.getAllStorages(SharedStorageHandler.java:139)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.tileentity.TileEntityMachine.func_145845_h(TileEntityMachine.java:250)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:20)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:30)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.FluidSharedStorage$Tank.<init>(FluidSharedStorage.java:22)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.FluidSharedStorage.<init>(FluidSharedStorage.java:37)
[13:27:05] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 14 more
[13:27:05] [Server thread/WARN] [FML/]: ****************************************

**Comment by Deathlymad** [comment]
sorry to not pastebin the crash i forgot :(

**Comment by thraaawn** [comment]
Get the fluid-preview version from curseforge.

**Comment by Deathlymad** [comment]
thanks
