### ISSUE TITLE
Did you try and create a stack for an unregistered fluid?

### ISSUE THREAD

**Issue by Schiratz** [thraaawn/CompactMachines#119]
[20:07:36] [Server thread/DEBUG] [FML/]: Method org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.canAccept(Lnet/minecraftforge/fluids/FluidStack;)Z: Replacing GETFIELD fluidID with INVOKEVIRTUAL getFluidID
[20:07:36] [Server thread/DEBUG] [FML/]: Method org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.fill(Lnet/minecraftforge/fluids/FluidStack;Z)I: Replacing GETFIELD fluidID with INVOKEVIRTUAL getFluidID
[20:07:36] [Server thread/WARN] [FML/]: ****************************************
[20:07:36] [Server thread/WARN] [FML/]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[20:07:36] [Server thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:28)
[20:07:36] [Server thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
[20:07:36] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:20)
[20:07:36] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:30)
[20:07:36] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.FluidSharedStorage$Tank.<init>(FluidSharedStorage.java:22)
[20:07:36] [Server thread/WARN] [FML/]: *  at org.dave.CompactMachines.integration.fluid.FluidSharedStorage.<init>(FluidSharedStorage.java:37)...
[20:07:36] [Server thread/WARN] [FML/]: ****************************************
[20:07:36] [Server thread/ERROR] [Compact Machines/]: Could not create instance of class: class org.dave.CompactMachines.integration.fluid.FluidSharedStorage
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.handler.SharedStorageHandler.getStorage(SharedStorageHandler.java:161)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.handler.SharedStorageHandler.getStorage(SharedStorageHandler.java:146)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.handler.SharedStorageHandler.getAllStorages(SharedStorageHandler.java:139)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.tileentity.TileEntityMachine.func_145845_h(TileEntityMachine.java:250)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:20)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:30)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.FluidSharedStorage$Tank.<init>(FluidSharedStorage.java:22)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.dave.CompactMachines.integration.fluid.FluidSharedStorage.<init>(FluidSharedStorage.java:37)
[20:07:36] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more
[20:07:36] [Server thread/WARN] [FML/]: ****************************************

**Comment by Schiratz** [comment]
This spammed the server console until the server crashed.
I just placed any of the compact machine blocks.

**Comment by Schiratz** [comment]
The new 1.19 Version fixed the Problem
