### ISSUE TITLE
ERR

### ISSUE THREAD

**Issue by ternsip** [thraaawn/CompactMachines#179]
Time: 5/28/16 4:10 PM
Description: Updating screen events

java.lang.StackOverflowError: Updating screen events
    at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:148)
    at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
    at cofh.lib.util.helpers.InventoryHelper.mergeItemStack(InventoryHelper.java:360)
    at net.minecraft.inventory.Container.func_75135_a(SourceFile)
    at org.dave.CompactMachines.inventory.ContainerMachine.func_82846_b(ContainerMachine.java:231)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:193)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:199)
    at net.minecraft.inventory.Container.func_75133_b(SourceFile:365)

**Comment by ternsip** [comment]
compactmachines-1.7.10-1.21

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.

**Comment by ternsip** [comment]
ooh, okay
