### ISSUE TITLE
Internal Server Error sometimes when connecting to a server

### ISSUE THREAD

**Issue by Eufranio** [thraaawn/CompactMachines#190]
Sometimes, when my players/me connects with my server, we get and `Internal Server Error` and are kicked with the following stacktrace:

```
[15:39:48] [Client thread/INFO]: Registering dimension 2 on client side
[15:39:48] [Client thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:118) ~[DimensionManager.class:?]
	at org.dave.CompactMachines.network.MessageConfiguration.onMessage(MessageConfiguration.java:46) ~[MessageConfiguration.class:?]
	at org.dave.CompactMachines.network.MessageConfiguration.onMessage(MessageConfiguration.java:14) ~[MessageConfiguration.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by MJRLegends** [comment]
You have a dimension already on the dimension id of 2, you can change it from the compact machines config

**Comment by Eufranio** [comment]
Yes I have, I have the Compact Machines dimension. Both client and server are with the same configs, in the server the Machines dimension is 2, and in client too...

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.

**Comment by Eufranio** [comment]
No backport?

**Comment by thraaawn** [comment]
Rewrite. Lots of things will change. No backport, sorry.

**Comment by Eufranio** [comment]
Ok, it was a nice mod :smile:
