### ISSUE TITLE
Client crash if Compact Machine block is broken with Tinker's Construct tool's

### ISSUE THREAD

**Issue by marduv** [thraaawn/CompactMachines#59]
Hi
If I break a Compact Machine block with my Tinker pickax, my client crashes.
Below is a copy of the crash log, let me know if there is something more you need to know or like me to test.

I hop this is something you can fix :-)
## Crash log:

java.lang.NullPointerException: Unexpected error
    at org.dave.CompactMachines.block.BlockMachine.removedByPlayer(BlockMachine.java:158)
    at tconstruct.library.tools.HarvestTool.mineBlock(HarvestTool.java:314)
    at tconstruct.library.tools.HarvestTool.onBlockStartBreak(HarvestTool.java:88)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:96)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
    at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1346)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1956)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at org.dave.CompactMachines.block.BlockMachine.removedByPlayer(BlockMachine.java:158)
    at tconstruct.library.tools.HarvestTool.mineBlock(HarvestTool.java:314)
    at tconstruct.library.tools.HarvestTool.onBlockStartBreak(HarvestTool.java:88)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:96)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
    at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1346)

**Comment by phoxmeh** [comment]
I just encountered this same issue today.

Seems, so far it is any tinker's pickaxe I have tried on regular CMs, the upgraded ones have no issue but a visual duplication which I've yet to check if that was fixed.

I'm currently using the 1.17 release of CM with forge 1291.

**Comment by thraaawn** [comment]
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.
