### ISSUE TITLE
Client crash if not player config dimension are the same as the server side :-(

### ISSUE THREAD

**Issue by marduvGitHub** [thraaawn/CompactMachines#63]
Hi
If the client config is set to the default dimension 2 and in my case the server side is set to 200 because I have dimension conflicting with a other mod, the client side crashes.
In order to fix this i need to edit the player data file so he/she spawn in overworld, after setting the player config file to the same dimension as the server.

I do get to types of error:
---------------------------------------------------------------------------------------
ava.lang.IllegalArgumentException: Could not get provider type for dimension 200, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:865)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:865)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

On second attempt if the config are NOT changed
---------------------------------------------------------------------------------------
java.lang.IllegalArgumentException: Could not get provider type for dimension -56, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:237)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:237)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

**Comment by UkeFox** [comment]
I, too have the same issue. Server kept crashing with the default dim id. Mystcraft uses positive dims so I set mine to -95. Server started but I crashed when using the psd on a machine. marduv's suggestion did the trick.
