### ISSUE TITLE
client timeout when trying to create new largest cube

### ISSUE THREAD

**Issue by nightstalker6669** [thraaawn/CompactMachines#93]
i'm testing out your mod and i've run into this error.

java.lang.NullPointerException
        at org.dave.CompactMachines.handler.machinedimension.MachineHandler.createChunk(MachineHandler.java:531) ~[MachineHandler.class:?]
        at org.dave.CompactMachines.handler.machinedimension.MachineHandler.teleportPlayerToMachineWorld(MachineHandler.java:368) ~[MachineHandler.class:?]
        at org.dave.CompactMachines.block.BlockMachine.func_149727_a(BlockMachine.java:223) ~[BlockMachine.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:456) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

it happens when i put down the biggest cube and try to click into it. when i log back into my test server i am still at the spot where i placed it down. i click into it again and get teleported, but there is no room, just the sky.

this is using your latest build, and forge 1343. i tried changing the dimension ID in the client and server side config, and it created the room once, but when i place a second cube down and click into it, it happens all over again.

**Comment by thraaawn** [comment]
I cannot reproduce this. Could you retry with v1.18 (or the latest build from [here](http://goo.gl/1ysU9U) if you are using Forge > 1355), please?
Also, something must be different on your server than on others - since your bug basically says the mod would be fundamentally broken. Any idea what it might be?

**Comment by nightstalker6669** [comment]
i will take a shot at your new build and see what it does. i am using cauldron, and there is a new build out for forge cauldron 1370, so i'll give it a shot.

**Comment by thraaawn** [comment]
Argh, cauldron. This issue existed before: cauldron forces worlds to unload even if they are programmed to not do that. You can configure this in your cauldron config and tell it to keep the Compact Machines dimension loaded.
